name: Run Non-Functional Tests

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run performance tests
      run: |
        pytest src/tests/performance -v
      env:
        DEVIN_API_URL: ${{ secrets.DEVIN_API_URL }}
        DEVIN_API_KEY: ${{ secrets.DEVIN_API_KEY }}
        
    - name: Run security tests
      run: |
        pytest src/tests/security -v
      env:
        DEVIN_API_URL: ${{ secrets.DEVIN_API_URL }}
        DEVIN_API_KEY: ${{ secrets.DEVIN_API_KEY }}
        
    - name: Generate HTML report
      run: |
        pytest --html=reports/report.html
        
    - name: Upload test report
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: reports/
